# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cordic.xdc

# Block Designs: bd/Cordic/Cordic.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic || ORIG_REF_NAME==Cordic} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_processing_system7_0_0/Cordic_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_processing_system7_0_0 || ORIG_REF_NAME==Cordic_processing_system7_0_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_cordic_0_1/Cordic_cordic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_cordic_0_1 || ORIG_REF_NAME==Cordic_cordic_0_1} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_xbar_0/Cordic_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_xbar_0 || ORIG_REF_NAME==Cordic_xbar_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_ps7_0_axi_periph_0/Cordic_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_ps7_0_axi_periph_0 || ORIG_REF_NAME==Cordic_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_rst_ps7_0_100M_0/Cordic_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_rst_ps7_0_100M_0 || ORIG_REF_NAME==Cordic_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_Roate_keyv2_0_0/Cordic_Roate_keyv2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_Roate_keyv2_0_0 || ORIG_REF_NAME==Cordic_Roate_keyv2_0_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_key_shake_0_0/Cordic_key_shake_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_key_shake_0_0 || ORIG_REF_NAME==Cordic_key_shake_0_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_xlconstant_0_0/Cordic_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_xlconstant_0_0 || ORIG_REF_NAME==Cordic_xlconstant_0_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_key_shake_0_1/Cordic_key_shake_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_key_shake_0_1 || ORIG_REF_NAME==Cordic_key_shake_0_1} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_key_shake_0_2/Cordic_key_shake_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_key_shake_0_2 || ORIG_REF_NAME==Cordic_key_shake_0_2} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_PmodOLED_0_0/Cordic_PmodOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_PmodOLED_0_0 || ORIG_REF_NAME==Cordic_PmodOLED_0_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_pmod_bridge_0_0/PmodOLED_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLED_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLED_pmod_bridge_0_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLED_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLED_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_gpio_0_0/PmodOLED_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLED_axi_gpio_0_0 || ORIG_REF_NAME==PmodOLED_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Cordic/ip/Cordic_auto_pc_0/Cordic_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cordic_auto_pc_0 || ORIG_REF_NAME==Cordic_auto_pc_0} -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_processing_system7_0_0/Cordic_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Cordic_processing_system7_0_0 || ORIG_REF_NAME==Cordic_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_rst_ps7_0_100M_0/Cordic_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Cordic_rst_ps7_0_100M_0 || ORIG_REF_NAME==Cordic_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_rst_ps7_0_100M_0/Cordic_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Cordic_rst_ps7_0_100M_0 || ORIG_REF_NAME==Cordic_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/Cordic_PmodOLED_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Cordic_PmodOLED_0_0 || ORIG_REF_NAME==Cordic_PmodOLED_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_ooc.xdc

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_pmod_bridge_0_0/PmodOLED_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLED_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLED_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLED_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLED_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLED_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLED_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLED_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLED_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_gpio_0_0/PmodOLED_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLED_axi_gpio_0_0 || ORIG_REF_NAME==PmodOLED_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_gpio_0_0/PmodOLED_axi_gpio_0_0_ooc.xdc

# XDC: bd/Cordic/ip/Cordic_PmodOLED_0_0/src/PmodOLED_axi_gpio_0_0/PmodOLED_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLED_axi_gpio_0_0 || ORIG_REF_NAME==PmodOLED_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Cordic/ip/Cordic_auto_pc_0/Cordic_auto_pc_0_ooc.xdc

# XDC: bd/Cordic/Cordic_ooc.xdc
